### PR TITLE
Restore compatibility with Rails 3

### LINKED ISSUE #27: Version 1.1.4 broken compatibility with Rails 3
The version 1.1.4 uses `before_action` instead of `before_filter` and this change breaks the compatibility with Rails 3. I think this information needs to be written in README or in the CHANGELOG to warning users that uses old Rails versions.

### PR DESCRIPTION
**Pull request by rhruiz**
Test if the controller responds to before_action or before_filter

Closes #27

### CODE REVIEW

**Comment by rhruiz** [comment]
@squiter if this works for you I will backport it to the 1.1 branch

**Comment by squiter** [comment]
It works @rhruiz ! I just opened the issue to warn new users :wink:

**Comment by rhruiz** [comment]
@fabioperrella

**Comment by fabioperrella** [comment]
it seems ok to me!

**Comment by fabioperrella** [comment]
why don't you add the tag for hacktoberfest ?

**Comment by rhruiz** [comment]
@fabioperrella as far as I know it is not required

**Comment by fabioperrella** [comment]
> @fabioperrella as far as I know it is not required

@rhruiz I'm not shure if is mandatory the label, take a look:

image

https://hacktoberfest.digitalocean.com/

**Pull request merged**
